// Builds src/content/worldmap.js. Needs: npm i --no-save d3-geo topojson-client world-atlas
// Usage: node scripts/gen_worldmap.mjs src/content/worldmap.js
import fs from 'fs'
import { geoNaturalEarth1, geoPath } from 'd3-geo'
import { feature } from 'topojson-client'
const topo = JSON.parse(fs.readFileSync(new URL('../node_modules/world-atlas/land-110m.json', import.meta.url), 'utf8'))
const land = feature(topo, topo.objects.land)
const W = 1000, H = 520
// frame the area we work in: Peru → Kazakhstan, Moscow → Zimbabwe
const frame = { type: 'Feature', geometry: { type: 'MultiPoint', coordinates: [[-84, -24], [86, 62], [-84, 62], [86, -24]] } }
const proj = geoNaturalEarth1().fitExtent([[0, 0], [W, H]], frame)
const path = geoPath(proj).digits(1)
const d = path(land)
const offices = [
  ['Srbija', 'Beograd', 44.817, 20.457, 'Evropa'],
  ['Bosna i Hercegovina', 'Bijeljina', 44.757, 19.215, 'Evropa'],
  ['Crna Gora', 'Herceg Novi', 42.453, 18.537, 'Evropa'],
  ['Rusija', 'Moskva', 55.756, 37.617, 'Evropa'],
  ['Alžir', 'Alžir', 36.715, 3.05, 'Afrika'],
  ['Gana', 'Akra', 5.603, -0.187, 'Afrika'],
  ['Gvineja', 'Konakri', 9.641, -13.578, 'Afrika'],
  ['Uganda', 'Kampala', 0.347, 32.582, 'Afrika'],
  ['Zimbabve', 'Harare', -17.829, 31.052, 'Afrika'],
  ['Zambija', 'Lusaka', -15.387, 28.322, 'Afrika'],
  ['Peru', 'Lima', -12.046, -77.043, 'Južna Amerika'],
  ['Katar', 'Doha', 25.286, 51.533, 'Bliski istok'],
  ['Oman', 'Muskat', 23.588, 58.383, 'Bliski istok'],
  ['UAE', 'Dubai', 25.205, 55.271, 'Bliski istok'],
  ['Bahrein', 'Manama', 26.229, 50.586, 'Bliski istok'],
  ['Kazahstan', 'Almati', 43.238, 76.946, 'Azija'],
].map(([country, city, lat, lon, region]) => { const [x, y] = proj([lon, lat]); return { country, city, region, x: +x.toFixed(1), y: +y.toFixed(1) } })
const out = `// Generated by scripts/gen_worldmap.mjs (d3-geo + world-atlas land-110m, Natural Earth projection). Do not edit by hand.
export const MAP_W = ${W}
export const MAP_H = ${H}
export const LAND = ${JSON.stringify(d)}
export const OFFICE_PINS = ${JSON.stringify(offices, null, 1)}
`
fs.writeFileSync(process.argv[2], out)
console.log('bytes', out.length, offices.map(o => o.city + ':' + o.x + ',' + o.y).join(' '))
